[RATOM-207] Modifies account list menu actions.
StateArchivesOfNorthCarolina/ratom-web pull request #70
Opened 2020-03-26 16:35 UTC by JeremyGibson

This fulfills the requirements of the ticket, but as always I'm a little unsure about best way to approach things. All feedback welcome.

Needs the backend piece in order to function.

2020-03-27 14:52 UTC, michael-caktus approved these changes

2020-03-27 15:49 UTC, michael-caktus approved these changes

2020-03-27 20:54 UTC, copelco requested changes
I think the Axios.delete params are slightly different for some reason.

Also, the merge conflict needs to be fixed.

2020-03-27 20:54 UTC, copelco commented on src/components/Containers/Accounts/AccountsList/AccountsListItem.js
> +    Axios.delete(DELETE_FILE, account)
```suggestion
    Axios.delete(DELETE_FILE, { data: account })
```

2020-03-30 14:49 UTC, copelco approved these changes

2020-03-30 14:54 UTC, merged